# Generated by Django 5.0.1 on 2024-01-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_attendance_alter_enrollment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='PhoneNumber',
            field=models.CharField(default='N/A', max_length=12),
        ),
    ]
